# リスク管理パラメータ詳細設定

position_level:
  stop_loss_pct: 5.0
  take_profit_stage1_pct: 15.0
  take_profit_stage2_pct: 25.0
  trailing_stop_pct: 3.0
  max_hold_time_hours: 72

portfolio_level:
  max_positions: 2
  daily_loss_limit: 5.0
  weekly_loss_limit: 10.0
  monthly_loss_limit: 15.0

system_level:
  circuit_breaker_pct: 10.0
  circuit_breaker_timeframe_min: 5
  max_api_retry: 3
  slippage_tolerance_pct: 3.0
